version: '3.8'
services:
  php-apache-environment:
    image: riqi/php
    container_name: php-apache
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8000:80
    networks:
      - backend-php

volumes:
  db:

networks:
  backend-php:
    name: backend-network-php
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24